services:
  #--- LOAD BALANCER ---
  nginx:
    image: nginx:alpine
    restart: always
    container_name: api-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    ports:
      - "9999:9999"
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"

  #--- BACKEND 1 ---
  backend1: &backend
    build:
      dockerfile: ./src/main/docker/Dockerfile.native-micro
    environment:
      QUARKUS_HTTP_PORT: 8080
      QUEUE_SIZE: 10000
      WORKERS: 25
      JNOSQL_DOCUMENT_DATABASE: payments
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://root:example@mongo:27017/payments?authSource=admin
      QUARKUS_MONGODB_MAX_POOL_SIZE: 25
      QUARKUS_MONGODB_MIN_POOL_SIZE: 25
      RETRIES_BEFORE_FALLBACK: 15
      DEFAULT_PAYMENT_URL: http://payment-processor-default:8080/payments
      FALLBACK_PAYMENT_URL: http://payment-processor-fallback:8080/payments
    depends_on:
      - mongo
    networks:
      - backend-net
      - payment-processor
    hostname: backend1
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "150MB"

  #--- BACKEND 2 ---
  backend2:
    <<: *backend
    hostname: backend2

  #--- DATABASE ---
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./init-index.js:/docker-entrypoint-initdb.d/init-index.js:ro
    environment:
      MONGO_INITDB_DATABASE: payments
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - backend-net
    hostname: mongo
    deploy:
      resources:
        limits:
          cpus: "0.90"
          memory: "180MB"

#--- NETWORKS ---
networks:
  backend-net:
    driver: bridge
  payment-processor:
    external: true