services:
  nginx:
    image: nginx:alpine
    restart: always
    container_name: quarkus-with-jedis-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    ports:
      - "9999:9999"
    networks:
      - quarkus-with-jedis-net
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "20MB"

  #--- BACKEND 1 ---
  backend1: &backend
    build:
      dockerfile: ./src/main/docker/Dockerfile.native-micro
    container_name: r2035-quarkus-with-jedis-01
    environment:
      - JEDIS_URL=redis://redis:6379
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080/payments
      - FALLBACK_PAYMENT_URL=http://payment-processor-fallback:8080/payments
      - RETRIES_BEFORE_FALLBACK=10000
      - INSTANCE_ID=backend-01
      - WORKERS_SIZE=13
      - JVM_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "5008:5005"
    networks:
      - quarkus-with-jedis-net
      - payment-processor
    depends_on:
      - redis
    hostname:  r2035-quarkus-with-jedis-01
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "65MB"

  #--- BACKEND 2 ---
  backend2:
    <<: *backend
    container_name: r2035-quarkus-with-jedis-02
    hostname:  r2035-quarkus-with-jedis-02
    environment:
      - JEDIS_URL=redis://redis:6379
      - DEFAULT_PAYMENT_URL=http://payment-processor-default:8080/payments
      - FALLBACK_PAYMENT_URL=http://payment-processor-fallback:8080/payments
      - RETRIES_BEFORE_FALLBACK=10000
      - INSTANCE_ID=backend-02
      - WORKERS_SIZE=13
      - JVM_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "5009:5005"

  #--- QUEUE AND STORAGE ---
  redis:
    image: redis:7.2-alpine
    container_name: r2025-quarkus-with-jedis-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6376:6379"
    networks:
      - quarkus-with-jedis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "200MB"
#--- NETWORKS ---
networks:
  quarkus-with-jedis-net:
    driver: bridge
  payment-processor:
    external: true